security:
  rules:
    - pattern: /admin/login

    - pattern: /admin/dashboard
      method: GET # matches any if not set
      roles: [STAFF, MANAGER, SUPER_ADMIN] # permit all if not set

    - pattern: /admin/users/**
      roles: [SUPER_ADMIN]

    - pattern: /admin/service-types/**
      roles: [SUPER_ADMIN]

    - pattern: /admin/applications/**
      roles: [STAFF, MANAGER, SUPER_ADMIN]

    - pattern: /admin/departments/**
      roles: [SUPER_ADMIN]
